name: nutritrack_shared
description: "Shared core, domain models and repositories for NutriTrack mobile and desktop apps."
publish_to: "none"

version: 1.0.0

environment:
  sdk: ^3.10.1
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter

  # Core / data layer dependencies (shared by mobile & desktop)
  dio: ^5.6.0
  shared_preferences: ^2.3.1
  cross_file: ^0.3.5+1

  google_fonts: ^6.3.3

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
